### ISSUE TITLE
issue with numpy array casting and null-handling

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes-python#16]
(This partially already came up in #12)

When calling a process function: why are list arguments directly casted to numpy arrays? This automatic casting could remove some nuances in the input data (e.g. how to handle no-data, null, nan, ...)

For example: I'm working on unit tests about processes `all` and `any`, based on the examples in the openEO API spec.

> all(data = [false,null]) => false
> all(data = [true,null]) => true
> ...

The equivalent of Javascript `null` in Python is `None` (e.g. if you json-decode "null", you get Python `None`), but when I try this in current openeo-processes-python, I get failure:

```
>>> oeop.all_([True, None])

Traceback (most recent call last):
  File "<ipython-input-18-0dcc5f4e4a99>", line 1, in <module>
    oeop.all_([True, None])
  File "..../src/openeo_processes/utils.py", line 83, in fun_wrapper
    return cls_fun(*args, **kwargs)
  File "..../src/openeo_processes/logic.py", line 533, in exec_np
    nan_ar = np.isnan(data)
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

The cause is that the list `[True, None]`  is  cast to numpy array of dtype "Object" (because of the `None`), which does not support the `isnan` method.

Apparently the `all_` implementation expects the user to use `NaN` as translation for Javascript `null`, which is not exactly the same thing.

Can't we just drop the automatic casting from Lists to numpy arrays?
It's fine to keep the "numpy" oriented implementation of `All.exec_np`, but then it is at least possible to provide a `None`-compatible version of `All.exec_num`

**Comment by soxofaan** [comment]
Also note that `all` and `any` expect datatype `array<boolean|null>`, while usage of `np.nan` converts the whole thing to float64

**Comment by soxofaan** [comment]
Also, when I pass a list of booleans, I get a numpy float array instead of a single boolean, which is bit weird:

```
>>> oeop.all_([True, False])

array([0.], dtype=float32)
````

**Comment by claxn** [comment]
Mmh I agree, then we should remove the automatic casting for lists (except one wants to work explicitly with numpy arrays) and implement everything more specifically for each function. `None` should definitely be supported. @soxofaan As you have already identified the functions, where such inconsistencies occur, could you please update them or should we fix them?
