### ISSUE TITLE
Error if 'x' or 'y' missing in result

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-python#93]
If I reduce the `x` dimension, an error is thrown. This happens because in `save_result` we expect to have both `x` and `y` dimensions. The problem is in `refactor_data`.

Sample process graph:
```
{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "boa_sentinel_2",
        "spatial_extent": {
          "west": 11.101306940744163,
          "south": 46.168407903071454,
          "east": 11.101473927023527,
          "north": 46.168599741094745
        },
        "temporal_extent": [
          "2019-05-01T12:00:00Z",
          "2019-05-10T12:00:00Z"
        ],
        "bands": [
          "B04"
        ]
      }
    },
    "2": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "3"
        },
        "format": "NETCDF"
      },
      "result": true
    },
    "3": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "reducer": {
          "process_graph": {
            "1": {
              "process_id": "mean",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          }
        },
        "dimension": "x"
      }
    }
  },
  "parameters": []
}
```
log:

`[2022-03-01 09:56:34,407] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653.odc_job 2022-03-01T09:55:53+00:00 [queued]> [2022-03-01 09:56:34,432] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653.odc_job 2022-03-01T09:55:53+00:00 [queued]> [2022-03-01 09:56:34,432] {{taskinstance.py:866}} INFO - -------------------------------------------------------------------------------- [2022-03-01 09:56:34,432] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1 [2022-03-01 09:56:34,432] {{taskinstance.py:868}} INFO - -------------------------------------------------------------------------------- [2022-03-01 09:56:34,450] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): odc_job> on 2022-03-01T09:55:53+00:00 [2022-03-01 09:56:34,457] {{standard_task_runner.py:53}} INFO - Started process 25786 to run task [2022-03-01 09:56:34,544] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653.odc_job 2022-03-01T09:55:53+00:00 [running]> e750f3211937 [2022-03-01 09:56:39,540] {{taskinstance.py:1128}} ERROR - proj_create: Open of /opt/conda/share/proj failed proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode Traceback (most recent call last): File "/data_out/us-ecf0c7ee-8dc8-4da8-a533-e74113a3ace2/jobs/jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653/jr-20220301T095134695481/odc_job/odc_job.py", line 14, in <module> _2_1 = oeop.save_result(**{'data': _3_2, 'format': 'NETCDF', 'output_filepath': '/data_out/us-ecf0c7ee-8dc8-4da8-a533-e74113a3ace2/jobs/jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653/jr-20220301T095134695481/odc_job/out'}) File "/usr/local/openeo-processes-python/src/openeo_processes/utils.py", line 116, in fun_wrapper return cls_fun(*args, **kwargs) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 275, in exec_xar data_list = refactor_data(data) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 253, in refactor_data all_tmp.append(reformat_dataset(data_at_timestamp, timestamp)) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 232, in reformat_dataset tmp = tmp.transpose(*base_dims) File "/opt/conda/lib/python3.8/site-packages/xarray/core/dataset.py", line 4480, in transpose raise ValueError( ValueError: arguments to transpose (('y', 'x')) must be permuted dataset dimensions (('y',)) Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task result = task_copy.execute(context=context) File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute return_value = self.execute_callable() File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable return self.python_callable(*self.op_args, **self.op_kwargs) File "/usr/local/airflow/dags/dag_jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653.py", line 44, in exec_odc_job raise RuntimeError(stderr.decode()) RuntimeError: proj_create: Open of /opt/conda/share/proj failed proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode Traceback (most recent call last): File "/data_out/us-ecf0c7ee-8dc8-4da8-a533-e74113a3ace2/jobs/jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653/jr-20220301T095134695481/odc_job/odc_job.py", line 14, in <module> _2_1 = oeop.save_result(**{'data': _3_2, 'format': 'NETCDF', 'output_filepath': '/data_out/us-ecf0c7ee-8dc8-4da8-a533-e74113a3ace2/jobs/jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653/jr-20220301T095134695481/odc_job/out'}) File "/usr/local/openeo-processes-python/src/openeo_processes/utils.py", line 116, in fun_wrapper return cls_fun(*args, **kwargs) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 275, in exec_xar data_list = refactor_data(data) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 253, in refactor_data all_tmp.append(reformat_dataset(data_at_timestamp, timestamp)) File "/usr/local/openeo-processes-python/src/openeo_processes/cubes.py", line 232, in reformat_dataset tmp = tmp.transpose(*base_dims) File "/opt/conda/lib/python3.8/site-packages/xarray/core/dataset.py", line 4480, in transpose raise ValueError( ValueError: arguments to transpose (('y', 'x')) must be permuted dataset dimensions (('y',)) [2022-03-01 09:56:39,549] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=jb-2472e9fb-f685-4a4e-b0ba-1bd37582e653, task_id=odc_job, execution_date=20220301T095553, start_date=20220301T095634, end_date=20220301T095639 [2022-03-01 09:56:44,383] {{logging_mixin.py:112}} INFO - [2022-03-01 09:56:44,382] {local_task_job.py:103} INFO - Task exited with return code 1`

**Comment by ValentinaHutter** [comment]
Thank you for reporting this. I had a look at it and the problem actually is, that we need a dimension `x` with minimum 2 labels in order to get the resolution of the file to index it into the datacube. So therefore `save_result` always assumed the `x` axis to be in the dimensions. But of course there are processes where the `x` axis disappears, so I will continue working on it.

**Comment by clausmichele** [comment]
Indeed. This is particularly important to support aggregate_spatial or reduce_spatial for instance, since they return data without 'x' or 'y' coordinates
